DROP TABLE IF EXISTS USER;
  
CREATE TABLE USER (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(40) NOT NULL,
    type VARCHAR(20) NOT NULL,
    contact VARCHAR(15) NOT NULL,
    city VARCHAR(15) NOT NULL,
    state VARCHAR(20) NOT NULL,
    pincode INT NOT NULL,
    wallet_balance DOUBLE NOT NULL DEFAULT 0.0,
    is_premium TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));